# -*- coding: utf-8 -*-
"""projeto-desenhando-emojis-com-dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TMncHD5vHGXNKJVvaFjie3Eu68xQl5H
"""

# =========================================================
# DESAFIO 1 - O Criador de Emojis (Pixels RGB)
# =========================================================

# Estrutura base para o exercício
emoji_data = {
    "nome": "Smile",
    "grade": [
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0
        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)], # Linha 1 (Olhos)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2
        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)], # Linha 3 (Boca)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]  # Linha 4
    ]
}

print("========== DESAFIO 1 ==========")

nova_grade = []

# 1º nível -> Dicionário
for chave, valor in emoji_data.items():

    # Trabalha apenas na grade
    if chave == "grade":

        # 2º nível -> Linhas
        for linha in valor:

            nova_linha = []

            # 3º nível -> Pixels
            for pixel in linha:

                # Verifica se o pixel é amarelo
                if pixel == (255, 255, 0):

                    # Aplicando sombra (50%)
                    novo_pixel = (
                        pixel[0] // 2,
                        pixel[1] // 2,
                        pixel[2] // 2
                    )

                else:
                    novo_pixel = pixel

                # adiciona pixel modificado
                nova_linha.append(novo_pixel)

            # adiciona linha nova
            nova_grade.append(nova_linha)

# Atualiza a grade do emoji
emoji_data["grade"] = nova_grade

print("Emoji com filtro de sombra:")
for linha in emoji_data["grade"]:
    print(linha)


# =========================================================
# DESAFIO 2 - Matrizes Musicais (Transposição)
# =========================================================

print("\n========== DESAFIO 2 ==========")

biblioteca_musical = {
    "Toques": [
        {"Alegre": ([440, 480], [520, 560])},
        {"Triste": ([200, 150], [100, 50])}
    ]
}

# 1º nível -> Dicionário principal
for chave, lista_musicas in biblioteca_musical.items():

    # 2º nível -> Lista de músicas
    for musica in lista_musicas:

        # 3º nível -> Dicionário interno
        for nome, matriz in musica.items():

            print(f"\nMúsica original: {nome}")
            print(matriz)

            # Fazendo a transposição da matriz
            matriz_transposta = []

            # Percorrendo colunas
            for coluna in range(len(matriz[0])):

                nova_linha = []

                # Percorrendo linhas
                for linha in range(len(matriz)):

                    nova_linha.append(matriz[linha][coluna])

                matriz_transposta.append(nova_linha)

            # Atualizando o dicionário com .update()
            musica.update({nome: matriz_transposta})

            print("Matriz transposta:")
            print(matriz_transposta)


# =========================================================
# DESAFIO 3 - O Integrador (Criação Livre)
# =========================================================

print("\n========== DESAFIO 3 ==========")

# Dicionário contendo playlist de imagens
playlist_imagens = {
    "Playlist": [
        {
            "nome": "Sol",
            "pixels": [
                [(255,255,0), (255,200,0)],
                [(255,150,0), (255,100,0)]
            ]
        },
        {
            "nome": "Lua",
            "pixels": [
                [(200,200,200), (150,150,150)],
                [(100,100,100), (50,50,50)]
            ]
        }
    ]
}

# Método de LISTA -> insert()
playlist_imagens["Playlist"].insert(1, {
    "nome": "Estrela",
    "pixels": [
        [(255,255,255), (255,255,100)],
        [(255,255,50), (255,255,0)]
    ]
})

# Método de DICIONÁRIO -> keys()
print("Chaves do dicionário:")
print(playlist_imagens.keys())

# 1º nível -> Dicionário
for chave, lista_imagens in playlist_imagens.items():

    # 2º nível -> Lista
    for imagem in lista_imagens:

        print(f"\nImagem: {imagem['nome']}")

        # 3º nível -> Pixels
        for linha in imagem["pixels"]:

            nova_linha = []

            for pixel in linha:

                # Exemplo de modificação:
                # escurecendo os pixels
                novo_pixel = (
                    pixel[0] // 2,
                    pixel[1] // 2,
                    pixel[2] // 2
                )

                # Método de LISTA -> append()
                nova_linha.append(novo_pixel)

            print(nova_linha)

# Método de LISTA -> pop()
imagem_removida = playlist_imagens["Playlist"].pop()

print("\nImagem removida com pop():")
print(imagem_removida["nome"])