# -*- coding: utf-8 -*-
"""projeto_engenharia_de_contexto_e_logica_fisica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TMncHD5vHGXNKJVvaFjie3Eu68xQl5H
"""

1 questao def classificar_iqa(iqa):

  match iqa:

    case _ if iqa <= 50:

      return "Boa"

    case _ if iqa <= 100:

      return "Moderada"

    case _ if iqa <= 150:

      return "Ruim"

    case _:

      return "Muito Ruim"





def calcular_conforto(temp, umidade, iqa):

  # Penalização por temperatura extrema (ideal ~25°C)

  conforto_temp = max(0, 10 - abs(temp - 25))



  # Umidade ideal entre 40 e 70

  if 40 <= umidade <= 70:

    conforto_umidade = 10

  else:

    conforto_umidade = max(0, 10 - abs(umidade - 55) / 2)



  # Penalização pelo IQA

  if iqa <= 50:

    conforto_iqa = 10

  elif iqa <= 100:

    conforto_iqa = 7

  elif iqa <= 150:

    conforto_iqa = 4

  else:

    conforto_iqa = 1



  # Média ponderada

  nota = (conforto_temp * 0.4 +

      conforto_umidade * 0.3 +

      conforto_iqa * 0.3)



  return round(nota, 2)

2 questao







def analisar_microclima(dados):

  for local in dados:

    nome = local[0]

    print(f"\n avenida_esperatina)



    horarios = ["Manhã",



    for i in range(len(local) - 1):

      temp, umidade, iqa = local[i + 1]



      classificacao = classificar_iqa(iqa)

      nota = calcular_conforto 15-minutos



      print(f"\n horas_ {14 horas)

      print(f" Temperatura: 24_ graus

      print(f" Umidade_2

      print(f"

      print(f" Nota de conforto_9





# Executar

analisar_microclima(dados_locais)

2 questão

locais = ["Quarto", "Corredor", "Sala", "Saida"]

estados = ["livre", "extintor", "porta_trancada", "livre"]



posicao = 0

energia = 10

tem_chave = False



print(atenção_niciando evacuação...\n")



while energia > 0:

  local_atual = locais[posicao]

  estado_atual = estados[posicao]



  print(f"Você está em: {local_atual}")

  print(f"Situação: {estado_atual}")



  # Verifica obstáculos

  if estado_atual == "livre":

    print("Caminho livre, avançando...")

    posicao += 1



  elif estado_atual == "extintor":

    print("Você encontrou um extintor! (pode ajudar)")

    tem_chave = True # exemplo de recurso coletado

    posicao += 1



  elif estado_atual == "porta_trancada":

    print(" Porta trancada!")



    # IF ANINHADO

    if tem_chave:

      print("Você tem a chave! Abrindo porta...")

      posicao += 1

    else:

      print("Sem chave! Voltando para procurar...")

      posicao -= 1



  else:

    print("atencão_ Obstáculo desconhecido!")



  energia -= 1

  print(f"Energia restante: {energia}\n")



  # Condição de saída

  if posicao == len(locais):

    print("correto_ Você conseguiu sair com segurança!")

    break



# Se acabar energia

if energia == 0:

  print(" Você ficou sem energia e não conseguiu sair.")

parte 3