# -*- coding: utf-8 -*-
"""sistema_de_auditoria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TMncHD5vHGXNKJVvaFjie3Eu68xQl5H
"""

import time


# =========================================================
# DECORATOR DE AUDITORIA
# =========================================================

def auditor(func):

    def wrapper(*args, **kwargs):

        print("\n" + "=" * 50)
        print("INICIANDO AUDITORIA DO ORÇAMENTO")
        print("=" * 50)

        # Exibe argumentos recebidos
        print(f"Argumentos posicionais (*args): {args[1:]}")
        print(f"Argumentos nomeados (**kwargs): {kwargs}")

        # Marca o tempo inicial
        inicio = time.time()

        # Executa a função original
        resultado = func(*args, **kwargs)

        # Marca o tempo final
        fim = time.time()

        # Calcula duração
        tempo_total = fim - inicio

        print("-" * 50)
        print(f"Tempo de execução: {tempo_total:.6f} segundos")
        print("AUDITORIA FINALIZADA")
        print("=" * 50)

        return resultado

    return wrapper


# =========================================================
# ESTRUTURA DA EMPRESA (DICIONÁRIO ANINHADO)
# =========================================================

empresa_data = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 50000,
                "Seguranca": 30000
            },
            "Desenvolvimento": {
                "Frontend": 20000,
                "Backend": 25000,
                "DevOps": 15000
            }
        },
        "RH": {
            "Recrutamento": 10000,
            "Treinamento": 12000,
            "Cultura": {
                "Eventos": 5000,
                "Brindes": 2000
            }
        },
        "Financeiro": 40000
    }
}


# =========================================================
# FUNÇÃO RECURSIVA
# =========================================================

@auditor
def calcular_orcamento(dados, *departamentos_ignorados, **kwargs):

    total = 0

    # Obtendo taxa de câmbio via kwargs
    taxa_cambio = kwargs.get("taxa_cambio", 1)
    moeda_destino = kwargs.get("moeda_destino", "BRL")

    # Função interna recursiva
    def somar_orcamento(estrutura):

        subtotal = 0

        # Percorre cada item do dicionário
        for chave, valor in estrutura.items():

            # Verifica se o departamento deve ser ignorado
            if chave in departamentos_ignorados:
                print(f"Departamento ignorado: {chave}")
                continue

            # Se for outro dicionário -> chama recursão
            if isinstance(valor, dict):
                subtotal += somar_orcamento(valor)

            # Se for número -> soma ao subtotal
            elif isinstance(valor, (int, float)):
                subtotal += valor

        return subtotal

    # Executa a recursão
    total = somar_orcamento(dados)

    # Aplica taxa de câmbio
    total_convertido = total * taxa_cambio

    print(f"\nMoeda destino: {moeda_destino}")
    print(f"Taxa de câmbio aplicada: {taxa_cambio}")

    return total_convertido


# =========================================================
# TESTES
# =========================================================

print("\nTOTAL GERAL DA EMPRESA:")
resultado1 = calcular_orcamento(
    empresa_data,
    moeda_destino="BRL",
    taxa_cambio=1
)

print(f"Orçamento total: R$ {resultado1:,.2f}")


print("\nTOTAL IGNORANDO RH:")
resultado2 = calcular_orcamento(
    empresa_data,
    "RH",
    moeda_destino="USD",
    taxa_cambio=0.19
)

print(f"Orçamento convertido: $ {resultado2:,.2f}")


print("\nTOTAL IGNORANDO TI E CULTURA:")
resultado3 = calcular_orcamento(
    empresa_data,
    "TI",
    "Cultura",
    moeda_destino="EUR",
    taxa_cambio=0.17
)

print(f"Orçamento convertido: € {resultado3:,.2f}")