# -*- coding: utf-8 -*-
"""projeto-traduzindo-logica-para-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TMncHD5vHGXNKJVvaFjie3Eu68xQl5H
"""

pisciocodigo 1 questao

def processar_vendas():

  total_compra = 0.0

  itens_comprados = 0



  quantidade_tipos = int(input("Quantos produtos diferentes foram comprados? "))



  for i in range(1, quantidade_tipos + 1):

    nome = input("Nome do produto: ")

    preco = float(input("Preço unitário: "))

    qtd = int(input("Quantidade deste produto: "))



    if preco <= 0 or qtd <= 0:

      print("Erro: Valores inválidos para", nome)

    else:

      subtotal = preco * qtd

      total_compra += subtotal

      itens_comprados += qtd



  if total_compra > 500:

    total_final = total_compra * 0.90

    print("Desconto de 10% aplicado!")

  elif total_compra > 200:

    total_final = total_compra * 0.95

  else:

    total_final = total_compra



  print("Resumo:", itens_comprados, "itens. Total a pagar: R$", total_final)





def analisar_clima():

  soma_temperaturas = 0.0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(1, 8):

    temp = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35:

      dias_quentes += 1



    if temp > 45 or temp < -5:

      alerta_extremo = True



  media = soma_temperaturas / 7



  print("Média semanal:", media)

  print("Dias acima de 35°C:", dias_quentes)



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")





def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos existem na turma? "))



  for j in range(1, total_alunos + 1):

    aluno_nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))



    media_aluno = (n1 + n2) / 2



    if media_aluno >= 7:

      print(aluno_nome, ": Aprovado com média", media_aluno)

    elif media_aluno >= 5:

      print(aluno_nome, ": Recuperação (Média:", media_aluno, ")")

    else:

      print(aluno_nome, ": Reprovado")





def simulador_poupanca():

  saldo = float(input("Valor inicial do investimento: "))

  taxa = float(input("Taxa de juros mensal (em %): "))

  meses = int(input("Número de meses da simulação: "))



  for m in range(1, meses + 1):

    aporte = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum) "))



    saldo += aporte

    juros = saldo * (taxa / 100)

    saldo += juros



    print(f"Mês {m}: Saldo atualizado = R$ {saldo}")



    if saldo > 10000:

      print(f"Parabéns! Você atingiu a meta de 10k no mês {m}")



  print(f"Resultado final após {meses} meses: R$ {saldo}")



2 questao

def analisar_clima():

  soma_temperaturas = 0.0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(1, 8):

    temp = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35:

      dias_quentes += 1



    if temp > 45 or temp < -5:

      alerta_extremo = True



  media = soma_temperaturas / 7



  print("Média semanal:", media)

  print("Dias acima de 35°C:", dias_quentes)



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")

3 questao

def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos existem na turma? "))



  for j in range(1, total_alunos + 1):

    aluno_nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))



    media_aluno = (n1 + n2) / 2



    if media_aluno >= 7:

      print(aluno_nome, ": Aprovado com média", media_aluno)

    elif media_aluno >= 5:

      print(aluno_nome, ": Recuperação (Média:", media_aluno, ")")

    else:

      print(aluno_nome, ": Reprovado")

questão 4

1 Se não usarmos int() ou float(), o input() retorna um valor do tipo string (texto). Isso faz com que operações matemáticas não funcionem corretamente, pois o Python pode interpretar os valores como texto e concatená-los em vez de realizar cálculos numéricos, ou até gerar erro em algumas operações.

2 sso ocorre porque o range() no Python não inclui o valor final (limite superior). Ou seja, ele vai até um número antes do especificado. Por isso, usamos meses + 1 para garantir que o último valor seja incluído, diferente do pseudocódigo que normalmente inclui o limite final automaticamente.