# -*- coding: utf-8 -*-
"""projeto-algoritimo-de-alditoria-de-dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TMncHD5vHGXNKJVvaFjie3Eu68xQl5H
"""

# -*- coding: utf-8 -*-
"""atividade 1

import statistics

def auditar_vendas():
    # 1. Definição Segura (Simulando uma constante interna para evitar manipulação)
    LIMITE_SEGURANCA = 10000.00

    print("--- Sistema de Monitoramento de Risco ---")

    try:
        # 2. Coleta de dados com Casting (Garantindo precisão matemática)
        v1 = float(input("Digite o valor da 1ª venda: "))
        v2 = float(input("Digite o valor da 2ª venda: "))
        v3 = float(input("Digite o valor da 3ª venda: "))

        vendas = [v1, v2, v3]

        # 3. Cálculos Estatísticos
        media_simples = sum(vendas) / len(vendas)
        mediana = statistics.median(vendas)

        print(f"\n[Análise] Média: R$ {media_simples:.2f}")
        print(f"[Análise] Mediana (Realidade): R$ {mediana:.2f}")

        # 4. Verificação de Outliers e Materialidade
        print("-" * 40)
        for i, valor in enumerate(vendas, 1):
            status = "NORMAL"
            alertas = []

            # Regra 1: Valor Absoluto (Limite de Segurança)
            if valor > LIMITE_SEGURANCA:
                status = "SUSPEITO"
                alertas.append(f"Ultrapassou teto de R$ {LIMITE_SEGURANCA}")

            # Regra 2: Discrepância (Fator 5x a Mediana)
            # Usamos a Mediana para evitar que o próprio outlier esconda a distorção
            if valor > (mediana * 5):
                status = "SUSPEITO"
                alertas.append(f"Discrepância detectada (5x a mediana)")

            # Exibição do Resultado por Item
            if status == "SUSPEITO":
                print(f"Venda {i} (R$ {valor:>8.2f}): [!] {status} - Motivo: {', '.join(alertas)}")
            else:
                print(f"Venda {i} (R$ {valor:>8.2f}): [✓] {status}")

    except ValueError:
        print("[Erro] Por favor, insira apenas números decimais separados por ponto.")

if __name__ == "__main__":
    auditar_vendas()
"""